
exports.DEFAULT_NETWORK_TECHNOLOGY = "neataptic";
exports.DEFAULT_ENABLE_RANDOM_NETWORK_TECHNOLOGY = true;

exports.DEFAULT_SEED_NETWORK_ID = false;
exports.DEFAULT_ENABLE_ZERO_SUCCESS_EVOLVE_OPTIONS = false;

exports.DEFAULT_USER_PROFILE_CHAR_CODES_ONLY_FLAG = false;
exports.DEFAULT_USER_PROFILE_CHAR_CODES_ONLY_PROBABILITY = 0.2;
exports.DEFAULT_USER_PROFILE_CHAR_CODES_ONLY_INPUTS_ID = "inputs_25250101_000000_255_profilecharcodes";

exports.DEFAULT_REMOVE_SEED_FROM_VIABLE_NN_SET_ON_FAIL = true;
exports.DEFAULT_USER_PROFILE_ONLY_FLAG = false;

exports.DEFAULT_BINARY_MODE = false;
exports.DEFAULT_BINARY_MODE_PROBABILITY = 0.5;
exports.DEFAULT_ENABLE_RANDOM_BINARY_MODE = true; // enableRandomBinaryMode

exports.DEFAULT_COMPARE_TECH = false;
exports.DEFAULT_FORCE_NETWORK_TECHNOLOGY = false;
exports.DEFAULT_VIABLE_NETWORK_TECHNOLOGY_ARRAY = ["tensorflow", "carrot", "neataptic"];

exports.DEFAULT_MAX_FAIL_NETWORKS = 50;
exports.DEFAULT_MIN_PASS_RATIO = 0.70;

exports.DEFAULT_ITERATIONS = 10;

exports.DEFAULT_RANDOM_EVOLVE_TECH_ARRAY = [
  "tensorflow",
  "carrot",
  "neataptic"
];

exports.DEFAULT_EVOLVE_THREADS = 4;
exports.DEFAULT_EVOLVE_ARCHITECTURE = "random";
exports.DEFAULT_EVOLVE_INPUTS_TO_HIDDEN_LAYER_SIZE_RATIO = 0.005;
exports.DEFAULT_EVOLVE_BEST_NETWORK = false;
exports.DEFAULT_EVOLVE_ERROR_THRESHOLD = 0.005;
exports.DEFAULT_EVOLVE_ERROR_THRESHOLD_RANGE = { min: 0.0, max: 1.0 };

exports.DEFAULT_TENSORFLOW_TRAIN_OPTIMIZER_ARRAY = [
  "SGD"
];

exports.DEFAULT_TENSORFLOW_TRAIN_LOSS_ARRAY = [
  "CATEGORICAL_CROSS_ENTROPY"
];

exports.DEFAULT_TENSORFLOW_TRAIN_METRICS_ARRAY = [
  "ACCURACY"
];

exports.DEFAULT_TENSORFLOW_TRAIN_INPUT_ACTIVATION_ARRAY = [
  "RELU"
];

exports.DEFAULT_TENSORFLOW_TRAIN_OUTPUT_ACTIVATION_ARRAY = [
  "SOFTMAX"
];

exports.DEFAULT_BRAIN_TRAIN_ACTIVATION_ARRAY = [
  "SIGMOID",
  "RELU",
  "LEAKY_RELU",
  "TANH"
];

exports.DEFAULT_EVOLVE_ACTIVATION = "LOGISTIC";
exports.DEFAULT_EVOLVE_ACTIVATION_ARRAY = [
  "ABSOLUTE",
  "BENT_IDENTITY",
  "BIPOLAR",
  "BIPOLAR_SIGMOID",
  "GAUSSIAN",
  "HARD_TANH",
  "IDENTITY",
  "LOGISTIC",
  "RELU",
  "SELU",
  "SINUSOID",
  "SOFTSIGN",
  "STEP",
  "TANH"
];

exports.DEFAULT_EVOLVE_COST = "MSE";
exports.DEFAULT_EVOLVE_COST_ARRAY = [
  "BINARY",
  "CROSS_ENTROPY",
  "HINGE",
  "MAE",
  "MAPE",
  "MSE",
  "WAPE"
];

exports.DEFAULT_EVOLVE_ELITISM = 1;
exports.DEFAULT_EVOLVE_ELITISM_RANGE = { min: 1, max: 5 };

exports.DEFAULT_EVOLVE_EQUAL = true;

exports.DEFAULT_EVOLVE_ERROR = 0.05;

exports.DEFAULT_EVOLVE_FITNESS_POPULATION = true;
exports.DEFAULT_EVOLVE_FITNESS_POPULATION_PROBABILITY = 0.5; // carrot only

exports.DEFAULT_EVOLVE_GROWTH = 0.0001;
exports.DEFAULT_EVOLVE_GROWTH_RANGE = { min: 0.00005, max: 0.00015 };

exports.DEFAULT_EVOLVE_LEARNING_RATE = 0.3;
exports.DEFAULT_EVOLVE_LEARNING_RATE_RANGE = { min: 0.0, max: 1.0 };

exports.DEFAULT_EVOLVE_LOG = 1;

exports.DEFAULT_EVOLVE_MOMENTUM = 0.1; // brain only
exports.DEFAULT_EVOLVE_MOMENTUM_RANGE = { min: 0.05, max: 0.5 }; // brain only

exports.DEFAULT_EVOLVE_EFFICIENT_MUTATION_PROBABILITY = 0.5; // carrot only
exports.DEFAULT_EVOLVE_EFFICIENT_MUTATION = false; // carrot only
// exports.DEFAULT_EVOLVE_MAX_NODES = 0; // carrot only
exports.DEFAULT_EVOLVE_MUTATION = "FFW"; // carrot and neataptic, specifies an array of possible mutations
exports.DEFAULT_EVOLVE_MUTATION_RATE = 0.4;
exports.DEFAULT_EVOLVE_MUTATION_RATE_RANGE = { min: 0.3, max: 0.75 };
exports.DEFAULT_EVOLVE_MUTATION_ARRAY = [ // carrot only
  "ADD_NODE",
  "SUB_NODE",
  "ADD_CONN",
  "SUB_CONN",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "MOD_ACTIVATION",
  "SWAP_NODES",
];

exports.DEFAULT_EVOLVE_POPSIZE = 20;

exports.DEFAULT_EVOLVE_SELECTION = "FITNESS_PROPORTIONATE";
exports.DEFAULT_EVOLVE_SELECTION_ARRAY = [
  "FITNESS_PROPORTIONATE",
  "POWER",
  "TOURNAMENT"
];

exports.DEFAULT_EVOLVE_PROVENANCE = 0;

exports.DEFAULT_BRAIN_TRAIN_TIMEOUT = Infinity;
